-- MariaDB schema for ClinicFlow
-- Execute this script after creating or selecting the database.
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CONSULTA_PROCEDIMENTO;
DROP TABLE IF EXISTS PROCEDIMENTO;
DROP TABLE IF EXISTS EXAME;
DROP TABLE IF EXISTS ANAMNESE;
DROP TABLE IF EXISTS CONSULTA;
DROP TABLE IF EXISTS DISPONIBILIDADE_ODONTOLOGO;
DROP TABLE IF EXISTS ODONTOLOGO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS DISPONIBILIDADE_MEDICO;
DROP TABLE IF EXISTS MEDICO;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tipo ENUM(
        'ADMIN',
        'RECEPCIONISTA',
        'ODONTOLOGO',
        'PACIENTE'
    ) NOT NULL
);
CREATE TABLE ESPECIALIDADE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE ODONTOLOGO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_usuario INT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    id_especialidade INT NOT NULL,
    cro VARCHAR(20) NOT NULL UNIQUE,
    salario DECIMAL(10, 2) NOT NULL CHECK (salario >= 0),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE DISPONIBILIDADE_ODONTOLOGO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_odontologo INT NOT NULL,
    dia_semana ENUM(
        'SEGUNDA',
        'TERCA',
        'QUARTA',
        'QUINTA',
        'SEXTA',
        'SABADO',
        'DOMINGO'
    ) NOT NULL,
    turno ENUM('MANHA', 'TARDE', 'NOITE') NOT NULL,
    CONSTRAINT uk_odontologo_dia_turno UNIQUE (id_odontologo, dia_semana, turno)
);
CREATE TABLE PACIENTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    cep VARCHAR(9) NULL,
    logradouro VARCHAR(100) NULL,
    numero_casa VARCHAR(10) NULL,
    bairro VARCHAR(50) NULL,
    cidade VARCHAR(50) NULL,
    estado VARCHAR(2) NULL,
    possui_plano_saude BOOLEAN NOT NULL DEFAULT FALSE,
    debito DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE ANAMNESE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_paciente INT NOT NULL UNIQUE,
    alergia BOOLEAN DEFAULT FALSE,
    descricao_alergia TEXT,
    diabetes BOOLEAN DEFAULT FALSE,
    hipertensao BOOLEAN DEFAULT FALSE,
    cardiopatia BOOLEAN DEFAULT FALSE,
    gestante BOOLEAN NULL,
    usa_medicacao BOOLEAN DEFAULT FALSE,
    descricao_medicacao TEXT,
    observacoes TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE CONSULTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_paciente INT NOT NULL,
    id_odontologo INT NOT NULL,
    id_usuario_responsavel INT NOT NULL,
    data_hora DATETIME NOT NULL,
    motivo VARCHAR(255),
    sintomas TEXT,
    observacoes_odontologicas TEXT,
    diagnostico_preliminar TEXT,
    valor DECIMAL(10, 2) NOT NULL CHECK (valor >= 0),
    prioridade ENUM('BAIXA', 'MEDIA', 'ALTA') NOT NULL DEFAULT 'MEDIA',
    status ENUM(
        'AGENDADA',
        'EM_ANDAMENTO',
        'CANCELADA',
        'FINALIZADA'
    ) NOT NULL DEFAULT 'AGENDADA',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE PROCEDIMENTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL CHECK (valor >= 0),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE CONSULTA_PROCEDIMENTO (
    id_consulta INT NOT NULL,
    id_procedimento INT NOT NULL,
    dente VARCHAR(10),
    quantidade INT DEFAULT 1 CHECK (quantidade > 0),
    observacoes TEXT,
    resultado TEXT,
    status ENUM(
        'SOLICITADO',
        'EM_ANALISE',
        'CONCLUIDO',
        'CANCELADO'
    ) NOT NULL DEFAULT 'SOLICITADO',
    PRIMARY KEY (id_consulta, id_procedimento)
);
ALTER TABLE CONSULTA_PROCEDIMENTO
ADD CONSTRAINT fk_consulta_procedimento_consulta FOREIGN KEY (id_consulta) REFERENCES CONSULTA(id),
    ADD CONSTRAINT fk_consulta_procedimento_procedimento FOREIGN KEY (id_procedimento) REFERENCES PROCEDIMENTO(id);
ALTER TABLE CONSULTA
ADD CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id),
    ADD CONSTRAINT fk_consulta_odontologo FOREIGN KEY (id_odontologo) REFERENCES ODONTOLOGO(id),
    ADD CONSTRAINT fk_consulta_usuario_responsavel FOREIGN KEY (id_usuario_responsavel) REFERENCES USUARIO(id);
ALTER TABLE ODONTOLOGO
ADD CONSTRAINT fk_odontologo_especialidade FOREIGN KEY (id_especialidade) REFERENCES ESPECIALIDADE(id),
    ADD CONSTRAINT fk_odontologo_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id);
ALTER TABLE DISPONIBILIDADE_ODONTOLOGO
ADD CONSTRAINT fk_disponibilidade_odontologo FOREIGN KEY (id_odontologo) REFERENCES ODONTOLOGO(id) ON DELETE CASCADE;
ALTER TABLE ANAMNESE
ADD CONSTRAINT fk_anamnese_paciente FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id) ON DELETE CASCADE;